---
abstract: 'Adds a modern REST API to RT under /REST/2.0/'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0
  Test::WWW::Mechanize::PSGI: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-REST2
no_index:
  directory:
    - inc
    - t
  package:
    - RT::Extension::REST2::Test
recommends:
  JSON::XS: 0
requires:
  Encode: 0
  JSON: 0
  Module::Path: 0
  Module::Runtime: 0
  Moose: 0
  MooseX::NonMoose: 0
  MooseX::Role::Parameterized: 0
  Path::Dispatcher: 0
  Plack::Builder: 0
  Pod::POM: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Web::Machine: '0.12'
  namespace::autoclean: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.04'
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.2.4
